sudo: required
services:
  - docker

before_install:
  - docker build -t shijilts/multidocker -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true shijilts/multidocker npm test

after_success:
  - docker build -t shijilts/multi-client ./client
  - docker build -t shijilts/multi-nginx  ./nginx
  - docker build -t shijilts/multi-server ./server
  - docker build -t shijilts/multi-worker ./worker


