sudo: required
services:
  - docker

before_install:
  - docker build -t shijilts/multidocker -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true shijilts/multidocker npm test

after_success:
  - docker build -t shijilts/multi-client ./client
  - docker build -t shijilts/multi-nginx  ./nginx
  - docker build -t shijilts/multi-server ./server
  - docker build -t shijilts/multi-worker ./worker
  #login to docker
  - echo "DOCKER_PASS" | docker login -u "DOCKER_ID"  --password-stdin
  # push the images to docker hub
  - docker push shijilts/multi-client
  - docker push shijilts/multi-nginx
  - docker push shijilts/multi-server
  - docker push shijilts/multi-worker



